version: '3.7'

x-common: &common
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "2"

services:
  redis:
    image: redis:6-alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - data:/data
    <<: *common

volumes:
  data:
